const dummySongs = [
    {
      id: 1,
      title: "Starboy",
      artist: "The Weeknd",
      filesong: "/assets/music/newsong.mp3",
      duration: "4:16",
      cover: "https://www.usatoday.com/gcdn/authoring/authoring-images/2024/10/19/PNAS/75745344007-img-6314.jpg?crop=990,743,x0,y480", 
    },
    {
      id: 2,
      title: "Demons",
      artist: "Imagine Dragons",
      filesong: "/assets/music/newsong.mp3",
      duration: "5:24",
      cover: "https://d3lzcn6mbbadaf.cloudfront.net/media/details/ANI-20241201141041.jpg",
    },
    {
      id: 3,
      title: "Viva La Vida",
      filesong: "/assets/music/newsong.mp3",
      artist: "Coldplay",
      duration: "4:02",
      cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbdjisQ9qgYNCPBZ-2NpfhhJDb78R3UQR3iw&s",
    },
    {
      id: 4,
      title: "Shape of You",
      filesong: "/assets/music/newsong.mp3",
      artist: "Ed Sheeran",
      duration: "3:53",
      cover: "https://d3lzcn6mbbadaf.cloudfront.net/media/details/rajkumar_rao_main2022061516255320220713120225.jpg",
    },
    {
      id: 5,
      title: "Blinding Lights",
      filesong: "/assets/music/newsong.mp3",
      artist: "The Weeknd",
      duration: "3:20",
      cover: "https://m.media-amazon.com/images/I/61fzssfUphL.jpg",
    },
    {
      id: 6,
      title: "Bonita",
      artist: "Dua Lipa",
      duration: "3:23",
      filesong: "/assets/music/newsong.mp3",
      cover: "https://assets.telegraphindia.com/telegraph/2024/Sep/1725883332_listen.jpg",
    },
    {
      id: 7,
      title: "Happier",
      artist: "Marshmello ft. Bastille",
      filesong: "/assets/music/newsong.mp3",
      duration: "3:34",
      cover: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/I_Hit_It_First_single_cover.jpg/220px-I_Hit_It_First_single_cover.jpg",
    },
    {
      id: 8,
      title: "Closer",
      artist: "The Chainsmokers ft. Halsey",
      filesong: "/assets/music/newsong.mp3",
      duration: "4:05",
      cover: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/I_Hit_It_First_single_cover.jpg/220px-I_Hit_It_First_single_cover.jpg",
    },
    {
      id: 9,
      title: "Memories",
      filesong: "/assets/music/newsong.mp3",
      artist: "Maroon 5",
      duration: "3:09",
      cover: "https://ia600403.us.archive.org/BookReader/BookReaderImages.php?zip=/21/items/AllHit1001Songs/All%20Hit%201001%20Songs_jp2.zip&file=All%20Hit%201001%20Songs_jp2/All%20Hit%201001%20Songs_0000.jp2&id=AllHit1001Songs&scale=8&rotate=0",
    },
    {
      id: 10,
      title: "Bad Guy",
      artist: "Billie Eilish",
      filesong: "/assets/music/newsong.mp3",
      duration: "3:14",
      cover: "https://outspoken.newagebd.com/files/img/202405/d8f8071808dd68a5ab87b81f1ec52b9b.jpg",
    },
    {
      id: 11,
      title: "Rolling in the Deep",
      artist: "Adele",
      filesong: "/assets/music/newsong.mp3",
      duration: "3:48",
      cover: "https://cdn01.justjared.com/wp-content/uploads/headlines/2023/04/taylor-swift-eras-tour-handwritten-set-list.jpg",
    },
    {
      id: 12,
      title: "Viva La Vida",
      artist: "Coldplay",
      filesong: "/assets/music/newsong.mp3",
      duration: "4:02",
      cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbdjisQ9qgYNCPBZ-2NpfhhJDb78R3UQR3iw&s",
    },
    {
      id: 13,
      title: "Someone Like You",
      artist: "Adele",
      filesong: "/assets/music/newsong.mp3",
      duration: "4:45",
      cover: "https://cdn01.justjared.com/wp-content/uploads/headlines/2023/04/taylor-swift-eras-tour-handwritten-set-list.jpg",
    },
  ];
  
  export default dummySongs;
  